# **컴프리헨션 & 람다**

* **for문 1~10 짝수만 출력**

In [7]:
for v in range(1,11) :
    if v % 2 == 0 :
        print(v, end=" ")

2 4 6 8 10

In [8]:
[v for v in range(1,11)if (v % 2 == 0)] #다 한 줄에 나열하고, 내가 찾을 값을 맨 앞으로 보낸다.

[2, 4, 6, 8, 10]

* <b>for문 1~5 3보다크면 *2, 그렇지 않으면 값 출력

In [15]:
for v in range(1,6):
    if v >3:
        print(v*2)
    else :
        print(v)

1
2
3
8
10

In [17]:
[(v*2) if (v>3) else (v) for v in range(1,6)]

[1, 2, 3, 8, 10]

# **람다(Lambda)**
* 익명(이름없는) 함수
* 1회용

* <b>함수이름: add
* 파라미터: 숫자2개 
* 결과 합리턴

In [27]:
def add(a,b) :
    res = a+b
    return res

c = add(4, 5)
print(c)

9

In [29]:
def ncheck(n) :
    print(n*2)

ncheck(6)

12

* <b> 람다 예제

In [37]:
ncheck2 = lambda n : n*2

In [38]:
ncheck(6)

12

In [39]:
ncheck2(6)

12

* <b> 람다 예제

In [ ]:
def add(a,b) :
    res = a+b
    return res

c = add(4, 5)
print(c)

In [42]:
add2 = lambda a,b : a+b
print(add2(1, 3)) #print 해도 되고 안해도 되고~ "a="으로 바꿔도 되고 안바꿔도 되고~

4

* <b> 람다 예제

In [48]:
a = lambda n : n if n > 10 else 0
a(30)

30

* <b> 람다 예제

In [50]:
def add(a) :
    res = a+10
    return res

a = lambda a : add(a)
a(5)

15

In [ ]:
a = lambda a : add(a)
a(5)

* <b> 람다 예제

In [58]:
def check(n1) : 
    res = 0
    if n1 >10:
        res = n1*2
    else :
        res = n1
    return res

check(2)

2

In [60]:
a= lambda n1 : check(n1)
a(3)

3

In [54]:
def check(mylist) : 
    res = 
    temp = []
    for v in mylist :
        if v >10:
            temp.append(v*2)
        else :
            temp.append(v)
    return temp

check([2,3,4,5])

5

# **DataFrame을 활용한 Lambda**

In [63]:
import numpy  as np 
import pandas as pd

In [64]:
df = pd.DataFrame({
    "name": ["kim", "hong", "park"],
    "age": [20, 25, 30]
})
df

   name  age
0   kim   20
1  hong   25
2  park   30

In [65]:
df["age"] = df["age"]+10
df

   name  age
0   kim   30
1  hong   35
2  park   40

In [66]:
df["age"] = df["age"].apply(lambda a: a+10)
df

   name  age
0   kim   40
1  hong   45
2  park   50