# **DataFrame 활용**

In [10]:
import numpy  as np #pandas와 numpy는 세트야!!
import pandas as pd

In [9]:
emp = pd.read_csv("../datas/emp.csv")
emp

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     NaN      20
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     NaN      30
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     NaN      20
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     NaN      10

In [8]:
dept = pd.read_csv("../datas/dept.csv")
dept

   DEPTNO       DNAME       LOC
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

# Viewing Date

emp.info()
emp.shape : 행*열
emp.index : 인덱스
emp.columns : 컬럼이름
emp.head() / emp.tail()

In [11]:
emp.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   EMPNO     14 non-null     int64
 1   ENAME     14 non-null     str
 2   JOB       14 non-null     str
 3   MGR       13 non-null     float64
 4   HIREDATE  14 non-null     str
 5   SAL       14 non-null     int64
 6   COMM      4 non-null      float64
 7   DEPTNO    14 non-null     int64
dtypes: float64(2), int64(3), str(3)
memory usage: 1.0 KB

In [14]:
emp.shape

(14, 8)

In [15]:
emp.index

RangeIndex(start=0, stop=14, step=1)

In [16]:
emp.columns

Index(['EMPNO', 'ENAME', 'JOB', 'MGR', 'HIREDATE', 'SAL', 'COMM', 'DEPTNO'], dtype='str')

In [18]:
emp.head()

   EMPNO   ENAME       JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0   7369   SMITH     CLERK  7902.0  17-DEC-80   800     NaN      20
1   7499   ALLEN  SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2   7521    WARD  SALESMAN  7698.0  22-FEB-81  1250   500.0      30
3   7566   JONES   MANAGER  7839.0  02-APR-81  2975     NaN      20
4   7654  MARTIN  SALESMAN  7698.0  28-SEP-81  1250  1400.0      30

In [19]:
emp.tail()

    EMPNO   ENAME       JOB     MGR   HIREDATE   SAL  COMM  DEPTNO
9    7844  TURNER  SALESMAN  7698.0  08-SEP-81  1500   0.0      30
10   7876   ADAMS     CLERK  7788.0  23-MAY-87  1100   NaN      20
11   7900   JAMES     CLERK  7698.0  03-DEC-81   950   NaN      30
12   7902    FORD   ANALYST  7566.0  03-DEC-81  3000   NaN      20
13   7934  MILLER     CLERK  7782.0  23-JAN-82  1300   NaN      10

# **Selection**

* []
* df.at() df.iat()
* df.loc() df.iloc()

In [21]:
emp

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     NaN      20
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     NaN      30
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     NaN      20
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     NaN      10

In [28]:
emp[["EMPNO","ENAME"]]

    EMPNO   ENAME
0    7369   SMITH
1    7499   ALLEN
2    7521    WARD
3    7566   JONES
4    7654  MARTIN
5    7698   BLAKE
6    7782   CLARK
7    7788   SCOTT
8    7839    KING
9    7844  TURNER
10   7876   ADAMS
11   7900   JAMES
12   7902    FORD
13   7934  MILLER

In [30]:
emp.iloc[0:14, 0:2]

    EMPNO   ENAME
0    7369   SMITH
1    7499   ALLEN
2    7521    WARD
3    7566   JONES
4    7654  MARTIN
5    7698   BLAKE
6    7782   CLARK
7    7788   SCOTT
8    7839    KING
9    7844  TURNER
10   7876   ADAMS
11   7900   JAMES
12   7902    FORD
13   7934  MILLER

In [31]:
emp.iloc[:, 0:2]

    EMPNO   ENAME
0    7369   SMITH
1    7499   ALLEN
2    7521    WARD
3    7566   JONES
4    7654  MARTIN
5    7698   BLAKE
6    7782   CLARK
7    7788   SCOTT
8    7839    KING
9    7844  TURNER
10   7876   ADAMS
11   7900   JAMES
12   7902    FORD
13   7934  MILLER

In [32]:
emp.loc[:, "EMPNO":"ENAME"]

    EMPNO   ENAME
0    7369   SMITH
1    7499   ALLEN
2    7521    WARD
3    7566   JONES
4    7654  MARTIN
5    7698   BLAKE
6    7782   CLARK
7    7788   SCOTT
8    7839    KING
9    7844  TURNER
10   7876   ADAMS
11   7900   JAMES
12   7902    FORD
13   7934  MILLER

In [33]:
emp.iloc[[0,2,3,4,7],[0,1,5,7]]

   EMPNO   ENAME   SAL  DEPTNO
0   7369   SMITH   800      20
2   7521    WARD  1250      30
3   7566   JONES  2975      20
4   7654  MARTIN  1250      30
7   7788   SCOTT  3000      20

In [34]:
emp

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     NaN      20
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     NaN      30
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     NaN      20
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     NaN      10

In [41]:
#emp.iloc[1:4,2:4]
emp.loc[1:3,"JOB":"MGR"]

        JOB     MGR
1  SALESMAN  7698.0
2  SALESMAN  7698.0
3   MANAGER  7839.0

In [48]:
emp.loc[:,"DEPTNO"]

0     20
1     30
2     30
3     20
4     30
5     30
6     10
7     20
8     10
9     30
10    20
11    30
12    20
13    10
Name: DEPTNO, dtype: int64

In [51]:
emp[['COMM','DEPTNO']]
#emp.iloc[ : ,  [-2, -1]  ]
#emp.iloc[ : ,  -2 : ]
#emp.iloc[ : ,  6 : ]
#emp.loc[ : ,  ['COMM','DEPTNO']  ]
#emp.loc[ : ,  'COMM':'DEPTNO'  ]

      COMM  DEPTNO
0      NaN      20
1    300.0      30
2    500.0      30
3      NaN      20
4   1400.0      30
5      NaN      30
6      NaN      10
7      NaN      20
8      NaN      10
9      0.0      30
10     NaN      20
11     NaN      30
12     NaN      20
13     NaN      10

In [53]:
emp[["ENAME","SAL","DEPTNO"]]
#emp.iloc[:,[1,5,7]]
#emp.loc[:,["ENAME","SAL","DEPTNO"]]

     ENAME   SAL  DEPTNO
0    SMITH   800      20
1    ALLEN  1600      30
2     WARD  1250      30
3    JONES  2975      20
4   MARTIN  1250      30
5    BLAKE  2850      30
6    CLARK  2450      10
7    SCOTT  3000      20
8     KING  5000      10
9   TURNER  1500      30
10   ADAMS  1100      20
11   JAMES   950      30
12    FORD  3000      20
13  MILLER  1300      10

In [57]:
emp.iloc[[2,5,12,13],:]
#emp.loc[[2,5,12,13],:]

    EMPNO   ENAME       JOB     MGR   HIREDATE   SAL   COMM  DEPTNO
2    7521    WARD  SALESMAN  7698.0  22-FEB-81  1250  500.0      30
5    7698   BLAKE   MANAGER  7839.0  01-MAY-81  2850    NaN      30
12   7902    FORD   ANALYST  7566.0  03-DEC-81  3000    NaN      20
13   7934  MILLER     CLERK  7782.0  23-JAN-82  1300    NaN      10

In [62]:
emp.iloc[[2,5,12,13],0:3] #0:x->x개가 들어있다로 해석하면 쉬울 듯? [0,1,2]=3개
#emp.iloc[[2,5,12,13],[0,1,2]]
#emp.loc[[2,5,12,13],"EMPNO":"JOB"]
#emp.loc[[2,5,12,13],["EMPNO","ENAME","JOB"]]

    EMPNO   ENAME       JOB
2    7521    WARD  SALESMAN
5    7698   BLAKE   MANAGER
12   7902    FORD   ANALYST
13   7934  MILLER     CLERK

In [66]:
emp.iat[8,1]
#emp.at[8,"ENAME"]
#emp.iloc[8,1]
#emp.loc[8,"ENAME"]

'KING'

# **Missing data**
* 결측 : NaN , null, np.nan
* <font color=red><b>fillna() : 채우기(보간)
* <font color=red><b>dropna() : 버리기
* <font color=red><b>isna() : 결측체크

* 컬럼 별 결측 수

In [68]:
emp.isna().sum()

EMPNO        0
ENAME        0
JOB          0
MGR          1
HIREDATE     0
SAL          0
COMM        10
DEPTNO       0
dtype: int64

In [69]:
emp["SAL"]+emp["COMM"]

0        NaN
1     1900.0
2     1750.0
3        NaN
4     2650.0
5        NaN
6        NaN
7        NaN
8        NaN
9     1500.0
10       NaN
11       NaN
12       NaN
13       NaN
dtype: float64

* COMM이 NaN이면 0으로 보간

In [75]:
#emp = emp.fillna(0) 전체를 다 채우는게 아니다 XXXXX
emp["COMM"].fillna(0)

0        0.0
1      300.0
2      500.0
3        0.0
4     1400.0
5        0.0
6        0.0
7        0.0
8        0.0
9        0.0
10       0.0
11       0.0
12       0.0
13       0.0
Name: COMM, dtype: float64

In [76]:
emp["COMM"]=emp["COMM"].fillna(0)

In [77]:
emp["SAL"]+emp["COMM"]

0      800.0
1     1900.0
2     1750.0
3     2975.0
4     2650.0
5     2850.0
6     2450.0
7     3000.0
8     5000.0
9     1500.0
10    1100.0
11     950.0
12    3000.0
13    1300.0
dtype: float64

* <b>emp에 연봉컬럼(YSAL) 추가하기
* YSAL = SAL*12 + COMM

In [82]:
emp["YSAL"]=emp["SAL"]*12+emp["COMM"]
emp

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO     YSAL
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     0.0      20   9600.0
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30  19500.0
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30  15500.0
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     0.0      20  35700.0
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30  16400.0
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     0.0      30  34200.0
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     0.0      10  29400.0
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     0.0      20  36000.0
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     0.0      10  60000.0
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30  18000.0
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     0.0      20  13200.0
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     0.0      30  11400.0
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     0.0      20  36000.0
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     0.0      10  15600.0

* 결측 삭제
* <b>"COMM"이 결측인 애들만 삭제

In [78]:
emp22 = pd.read_csv("../datas/emp.csv")
emp22

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     NaN      20
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     NaN      30
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     NaN      20
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     NaN      10

In [84]:
emp22=emp22.dropna(subset=["COMM"])

In [85]:
emp22

   EMPNO   ENAME       JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
1   7499   ALLEN  SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2   7521    WARD  SALESMAN  7698.0  22-FEB-81  1250   500.0      30
4   7654  MARTIN  SALESMAN  7698.0  28-SEP-81  1250  1400.0      30
9   7844  TURNER  SALESMAN  7698.0  08-SEP-81  1500     0.0      30

* <b>JOB, MGR 컬럼 삭제

In [96]:
emp22=emp22.drop(columns=["JOB"])

In [97]:
emp22=emp22.drop(columns=["MGR"])

In [98]:
emp22

   EMPNO   ENAME   HIREDATE   SAL    COMM  DEPTNO
1   7499   ALLEN  20-FEB-81  1600   300.0      30
2   7521    WARD  22-FEB-81  1250   500.0      30
4   7654  MARTIN  28-SEP-81  1250  1400.0      30
9   7844  TURNER  08-SEP-81  1500     0.0      30

# **stat.**

* 통계(statistics)

In [99]:
emp

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO     YSAL
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     0.0      20   9600.0
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30  19500.0
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30  15500.0
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     0.0      20  35700.0
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30  16400.0
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     0.0      30  34200.0
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     0.0      10  29400.0
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     0.0      20  36000.0
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     0.0      10  60000.0
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30  18000.0
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     0.0      20  13200.0
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     0.0      30  11400.0
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     0.0      20  36000.0
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     0.0      10  15600.0

In [101]:
emp.describe()

,EMPNO,MGR,SAL,COMM,DEPTNO,YSAL
count,14.000000,13.000000,14.000000,14.000000,14.000000,14.000000
mean,7726.571429,7739.307692,2073.214286,157.142857,22.142857,25035.714286
std,178.294361,103.714660,1182.503224,387.723704,8.017837,14083.957439
min,7369.000000,7566.000000,800.000000,0.000000,10.000000,9600.000000
25%,7588.000000,7698.000000,1250.000000,0.000000,20.000000,15525.000000
50%,7785.000000,7698.000000,1550.000000,0.000000,20.000000,18750.000000
75%,7868.000000,7839.000000,2943.750000,0.000000,30.000000,35325.000000
max,7934.000000,7902.000000,5000.000000,1400.000000,30.000000,60000.000000

* <font color=red><b>★★JOB별 사원수

In [107]:
emp["JOB"].describe() #이건 뭐임???

count        14
unique        5
top       CLERK
freq          4
Name: JOB, dtype: object

In [109]:
emp.groupby("JOB")["EMPNO"].count()

JOB
ANALYST      2
CLERK        4
MANAGER      3
PRESIDENT    1
SALESMAN     4
Name: EMPNO, dtype: int64

In [110]:
emp["JOB"].value_counts()

JOB
CLERK        4
SALESMAN     4
MANAGER      3
ANALYST      2
PRESIDENT    1
Name: count, dtype: int64

* <font color=red><b>★★각 부서(DEPTNO)별 JOB별 급여(SAL) 총합

In [118]:
emp.groupby(["DEPTNO", "JOB"])["SAL"].sum().reset_index()

   DEPTNO        JOB   SAL
0      10      CLERK  1300
1      10    MANAGER  2450
2      10  PRESIDENT  5000
3      20    ANALYST  6000
4      20      CLERK  1900
5      20    MANAGER  2975
6      30      CLERK   950
7      30    MANAGER  2850
8      30   SALESMAN  5600

* <font color=red><b>★★부서(DEPTNO)별 급여(SAL) 최소 / 최대

In [120]:
emp.groupby("DEPTNO")["SAL"].min()

DEPTNO
10    1300
20     800
30     950
Name: SAL, dtype: int64

In [119]:
emp.groupby("DEPTNO")["SAL"].max()

DEPTNO
10    5000
20    3000
30    2850
Name: SAL, dtype: int64

In [121]:
emp.groupby("DEPTNO")["SAL"].agg(["min","max"])

         min   max
DEPTNO
10      1300  5000
20       800  3000
30       950  2850

* <font color=red><b>★★부서(DEPTNO)별 급여(SAL) 최소 / 입사일(HIREDATE) 최대

In [123]:
emp.groupby("DEPTNO").agg({"SAL":"min","HIREDATE":"max"})

         SAL   HIREDATE
DEPTNO
10      1300  23-JAN-82
20       800  23-MAY-87
30       950  28-SEP-81

In [ ]:
df77.groupby("A").agg({"D":"min","E":"max"})